(() => {
    const letterSet = rows => rows.map(([letter,name,word,emoji]) => ({letter,name,word,emoji}));

    window.extraLanguagePacks = {
        de: {
            code:'de-DE', flag:'🇩🇪', picker:'🇩🇪 Deutschland — Deutsch',
            foods:['Apfel','Banane','Pizza','Karotte','Eis','Erdbeere','Keks','Wassermelone','Brokkoli','Trauben','Orange','Birne','Ananas','Avocado','Mais','Taco','Brot','Käse','Ei','Milch','Tomate','Kartoffel','Kirschen','Pfirsich','Mango','Zitrone','Hotdog'],
            santaFoods:['den Apfel','die Banane','die Pizza','die Karotte','das Eis','die Erdbeere','den Keks','die Wassermelone','den Brokkoli','die Trauben','die Orange','die Birne','die Ananas','die Avocado','den Mais','den Taco','das Brot','den Käse','das Ei','die Milch','die Tomate','die Kartoffel','die Kirschen','den Pfirsich','die Mango','die Zitrone','den Hotdog'],
            trucks:['Traktor','Kran','Bagger','Muldenkipper','Feuerwehrauto','Planierraupe','Krankenwagen','Rakete','Baggerlader','Radlader','Straßenwalze','Betonmischer','Müllwagen','Abschleppwagen','Schneepflug','Gabelstapler','Kompaktlader','Straßenfertiger','Bohrgerät','Monstertruck','Polizeiauto','Schulbus','Lieferwagen','Zug'],
            animals:['Hund','Katze','Löwe','Kuh','Frosch','Ente','Schaf','Schweinchen','Pferd','Elefant','Äffchen','Tiger','Bär','Hase','Huhn','Hahn','Ziege','Esel','Eule','Pinguin','Giraffe','Zebra','Krokodil','Wal'],
            numbers:['Eins','Zwei','Drei','Vier','Fünf','Sechs','Sieben','Acht','Neun','Zehn','Elf','Zwölf','Dreizehn','Vierzehn','Fünfzehn','Sechzehn','Siebzehn','Achtzehn','Neunzehn','Zwanzig'],
            everyday:['Strohhalm','Glas Milch','Teller','Schüssel','Löffel','Gabel','Serviette','Babyflasche','Pfanne','Topf','Eiswürfel','Stuhl','Zahnbürste','Seife','Socke','Schuh','Bett','Badewanne','Tür','Schlüssel'],
            everydayPrompts:['den Strohhalm','das Glas Milch','den Teller','die Schüssel','den Löffel','die Gabel','die Serviette','die Babyflasche','die Pfanne','den Topf','den Eiswürfel','den Stuhl','die Zahnbürste','die Seife','die Socke','den Schuh','das Bett','die Badewanne','die Tür','die Schlüssel'],
            instruments:['Schlagzeug','Gitarre','Keyboard','Glocken','Maracas','Handtrommel','Trompete','Mikrofon','Geige','Saxofon','Flöte','Akkordeon','Banjo'],
            colors:['rot','blau','gelb','grün'], shapes:['Kreis','Quadrat','Dreieck','Stern','Herz'],
            body:['Kopf','Ohren','Augen','Nase','Mund','Bauch','Arm','Hand · Finger','Finger','Knie','Bein','Fuß · Zehen','Zehen'],
            runnerFoods:['Brokkoli','Tomate','Karotte','Apfel','Banane','Erdbeere','Orange','Mais','Birne','Trauben','Wassermelone','Ananas','Avocado','Kirschen','Zitrone','Kartoffel','Pfirsich','Mango','Paprika','Gurke','Aubergine','Süßkartoffel','Kiwi','Blaubeeren'],
            bellNotes:['C','D','E','F','G'],
            letters:letterSet([
                ['A','A','Apfel','🍎'],['B','Be','Ball','⚽'],['C','Ce','Clown','🤡'],['D','De','Dino','🦖'],['E','E','Elefant','🐘'],['F','Ef','Fisch','🐟'],['G','Ge','Gitarre','🎸'],['H','Ha','Haus','🏠'],['I','I','Igel','🦔'],['J','Jot','Jacke','🧥'],['K','Ka','Katze','🐱'],['L','El','Löwe','🦁'],['M','Em','Mond','🌙'],['N','En','Nest','🪺'],['O','O','Orange','🍊'],['P','Pe','Pinguin','🐧'],['Q','Ku','Qualle','🪼'],['R','Er','Regenbogen','🌈'],['S','Es','Sonne','☀️'],['T','Te','Tiger','🐯'],['U','U','Uhr','🕐'],['V','Vau','Vogel','🐦'],['W','We','Wal','🐋'],['X','Ix','Xylophon','🎶'],['Y','Ypsilon','Yoga','🧘'],['Z','Zett','Zebra','🦓'],['Ä','Ä','Äpfel','🍎'],['Ö','Ö','Öl','🫗'],['Ü','Ü','Überraschung','🎁'],['ß','Eszett','Fuß','🦶']
            ]),
            interface:{
                pageTitle:'Toddler Arcade',allLanguages:'Alle 12',feedSanta:'Füttere den Weihnachtsmann',trucks:'Große Fahrzeuge',balloons:'Zahlenballons',animals:'Tiere',chooseGame:'Such ein Spiel aus',previousGame:'Vorheriges Spiel',nextGame:'Nächstes Spiel',chooseLanguage:'Sprache',gamesLabel:'Spiele',menuLabel:'Spielmenü',playNow:'Jetzt spielen',swipeForGames:'Wische für mehr Spiele',hideControls:'Steuerung ausblenden',showControls:'Spiele und Sprachen',randomGame:'Überraschungsspiel',randomLanguageGame:'Überraschungsspiel und -sprache',playTimer:'Spielzeit einstellen',playTimerTitle:'Spielzeit',playTimerPrompt:'Wie lange wollen wir spielen?',minutesShort:'Min.',noTimer:'Ohne Timer',cancel:'Abbrechen',timeUpTitle:'Fertig!',timeUpMessage:'Toll gespielt. Zeit für eine Pause!',moreTime:'Erwachsene: mehr Zeit',
                santaPrompt:'Ari was soll der Weihnachtsmann essen? 🎅',morePlease:'Was soll der Weihnachtsmann als Nächstes essen Ari? 🎅',tickle:'Ho ho ho! Das kitzelt Ari! 😆',santaLaugh:'Ho! Ho! Ho!',dragFood:'Zieh oder tippe auf ein Essen',popBalloons:'Lass die Ballons platzen! 🎈',popped:n=>`Ballon Nummer ${n} ist geplatzt! ⭐`,balloonLevelUp:n=>`Super! Jetzt von 1 bis ${n}! 🚀`,santaLabel:'Weihnachtsmann',
                everyday:'Alltagssachen',letters:'Buchstabengarten',shapes:'Farben und Formen',counting:'Zählen und wählen',body:'Mein Körper',runner:'Fang den Brokkoli',music:'Musikstudio',beat:'Muster nachspielen',dance:'Tanzen und Stopp',bells:'Weihnachtsglocken',everydayPrompt:'Entdecke sechs Dinge',everydayExplore:'👀 Entdecken',everydayFind:'👆 Tippen',everydayMore:'Mehr Dinge →',findQuestion:item=>`Tippe auf ${item}`,findTry:'Schau noch einmal',findFound:()=>`Genau das!`,findNext:'▶ Nächstes',findReal:()=>`Findest du so etwas in deiner Nähe?`,
                letterPrompt:'Tippe auf einen Buchstaben',letterPhrase:item=>`${item.name}. ${item.letter} wie ${item.word}.`,shapePrompt:(color,shape)=>`Tippe. Farbe ${color}. Form ${shape}.`,shapeTry:'Schau noch einmal',shapeGreat:'Gefunden!',countPrompt:'Wie viele?',countTry:'Zähl noch einmal',countGreat:n=>`${n}! Toll gezählt!`,bodyPrompt:'Tippe auf ein Körperteil',bodyHint:'Tippe auf die Figur',runnerPrompt:'Gedrückt halten zum Fliegen · Loslassen zum Landen',runnerHint:'Gedrückt halten zum Fliegen',runnerRotate:'Dreh das Handy zur Seite',runnerTutorial:'Gedrückt halten zum Fliegen · Loslassen zum Landen',runnerCaught:(food,score)=>`${food}! ${score === 1 ? 'Ein Punkt' : `${score} Punkte`}!`,runnerOw:'Au!',
                musicPrompt:'Mach Musik',musicTogether:'Spielt abwechselnd',beatPrompt:'Schau dir das Muster an',beatStart:'Tippe auf den tanzenden Bären',beatNext:'▶ Neues Muster',beatReady:'Bereit? Tippe auf den tanzenden Bären.',beatExplain:'Schau das Muster an. Spiel es dann nach. Bereit?',beatYourTurn:'Du bist dran!',beatGreat:'Du hast es dir gemerkt!',beatPraise:['Super!','Sehr gut!','Geschafft!','Klasse!'],beatAgain:'Schau dir dasselbe Muster noch einmal an',danceReady:'Bereit?',danceStart:'▶ Tanzen',danceStop:'■ Stopp',danceTogether:'Macht Platz und tanzt zusammen',bellsPrompt:'Spiel mit dem Weihnachtsmann',bellsSantaAction:'Hör den Weihnachtsmann',bellsBellAction:'Läute die große Glocke',jingleStart:'🎶 Jingle Bells spielen',jingleStop:'■ Lied stoppen'
            },
            settings:{button:'Elterneinstellungen',title:'Elterneinstellungen',greekNames:'🇬🇷 Namen auf Griechisch',otherNames:'🌍 Namen in den anderen Sprachen',help:'Trenne Spitznamen mit Kommas. Behalte in beiden Listen dieselbe Reihenfolge.',required:'Gib mindestens einen Namen ein.',error:'Beide Listen brauchen gleich viele Namen.',close:'Schließen',cancel:'Abbrechen',save:'Speichern',restore:'Standard wiederherstellen',setup:'🌍 Sprachen und Einrichtung',diceTitle:'🎲 Was macht der Würfel?',diceSingle:'Eine Sprache',diceMultilingual:'Alle Sprachen',diceRandom:'Zufällige Sprache',timer:'Spielzeit',soundCredits:'🔊 Quellen der echten Geräusche'},
            onboarding:{step:n=>`Schritt ${n} von 3`,primaryTitle:'Was ist die Hauptsprache des Spiels?',primaryLead:'Sie erscheint zuerst und wird für die Menüs verwendet.',languagesTitle:'Welche Sprachen soll dein Kind hören?',languagesLead:'Füge weitere Sprachen hinzu. Du kannst sie später ändern.',languageMain:'Hauptsprache',languageCount:n=>`${n} Sprachen aktiv`,addLanguage:'+ Weitere Sprache',allLanguagesAdded:'Alle Sprachen hinzugefügt',localeHint:'✨ Nach Sprache und Region des Geräts vorausgewählt',namesTitle:'Wie soll das Spiel dein Kind nennen?',namesLead:'Optional: Namen so eingeben wie sie gesprochen werden sollen oder überspringen.',greekLabel:'🇬🇷 Auf Griechisch',otherLabel:'🌍 In den anderen Sprachen',namesHelp:'Optional. Name und Spitznamen mit Kommas trennen.',back:'Zurück',next:'Weiter',finish:'Speichern und spielen',skipNames:'Jetzt überspringen',close:'Schließen',required:'Gib mindestens einen Namen ein.',mismatch:'Beide Listen brauchen gleich viele Namen.'},
            danceMoves:['Tanz!','Klatsch!','Lauf im Kreis!','Spring!','Dreh dich!','Hände hoch!'],freeze:'Stopp!',leader:'Du bist dran!',
            santaThanks:(food,foodName,name,variant)=>[
                `${food}! Danke für ${foodName} ${name}!`,
                `${food}! Das war lecker! Danke ${name}!`,
                `${food}! Das hat mir geschmeckt! Danke ${name}!`
            ][variant]
        },
        it: {
            code:'it-IT', flag:'🇮🇹', picker:'🇮🇹 Italia — Italiano',
            foods:['Mela','Banana','Pizza','Carota','Gelato','Fragola','Biscotto','Anguria','Broccolo','Uva','Arancia','Pera','Ananas','Avocado','Mais','Taco','Pane','Formaggio','Uovo','Latte','Pomodoro','Patata','Ciliegie','Pesca','Mango','Limone','Hot dog'],
            santaFoods:['la mela','la banana','la pizza','la carota','il gelato','la fragola','il biscotto','l’anguria','il broccolo','l’uva','l’arancia','la pera','l’ananas','l’avocado','il mais','il taco','il pane','il formaggio','l’uovo','il latte','il pomodoro','la patata','le ciliegie','la pesca','il mango','il limone','l’hot dog'],
            trucks:['Trattore','Gru','Escavatore','Camion ribaltabile','Camion dei pompieri','Bulldozer','Ambulanza','Razzo','Terna','Pala gommata','Rullo compressore','Betoniera','Camion dei rifiuti','Carro attrezzi','Spazzaneve','Muletto','Minipala','Finitrice stradale','Trivella','Monster truck','Auto della polizia','Scuolabus','Furgone delle consegne','Treno'],
            animals:['Cagnolino','Gattino','Leoncino','Mucca','Ranocchio','Anatroccolo','Pecorella','Maialino','Cavallino','Elefantino','Scimmietta','Tigrotto','Orsetto','Coniglietto','Gallina','Gallo','Capretta','Asinello','Gufo','Pinguino','Giraffa','Zebra','Coccodrillo','Balena'],
            numbers:['Uno','Due','Tre','Quattro','Cinque','Sei','Sette','Otto','Nove','Dieci','Undici','Dodici','Tredici','Quattordici','Quindici','Sedici','Diciassette','Diciotto','Diciannove','Venti'],
            everyday:['Cannuccia','Bicchiere di latte','Piatto','Ciotola','Cucchiaio','Forchetta','Tovagliolo','Biberon','Padella','Pentola','Cubetto di ghiaccio','Sedia','Spazzolino','Sapone','Calzino','Scarpa','Letto','Vasca da bagno','Porta','Chiavi'],
            everydayPrompts:['la cannuccia','il bicchiere di latte','il piatto','la ciotola','il cucchiaio','la forchetta','il tovagliolo','il biberon','la padella','la pentola','il cubetto di ghiaccio','la sedia','lo spazzolino','il sapone','il calzino','la scarpa','il letto','la vasca da bagno','la porta','le chiavi'],
            instruments:['Batteria','Chitarra','Tastiera','Campane','Maracas','Tamburo','Tromba','Microfono','Violino','Sassofono','Flauto','Fisarmonica','Banjo'],
            colors:['rosso','blu','giallo','verde'], shapes:['cerchio','quadrato','triangolo','stella','cuore'],
            body:['Testa','Orecchie','Occhi','Naso','Bocca','Pancia','Braccio','Mano · Dita','Dita','Ginocchio','Gamba','Piede · Dita dei piedi','Dita dei piedi'],
            runnerFoods:['Broccolo','Pomodoro','Carota','Mela','Banana','Fragola','Arancia','Mais','Pera','Uva','Anguria','Ananas','Avocado','Ciliegie','Limone','Patata','Pesca','Mango','Peperone','Cetriolo','Melanzana','Patata dolce','Kiwi','Mirtilli'], bellNotes:['Do','Re','Mi','Fa','Sol'],
            letters:letterSet([
                ['A','A','albero','🌳'],['B','Bi','banana','🍌'],['C','Ci','cane','🐶'],['D','Di','dinosauro','🦖'],['E','E','elefante','🐘'],['F','Effe','fiore','🌸'],['G','Gi','gatto','🐱'],['H','Acca','hotel','🏨'],['I','I','isola','🏝️'],['L','Elle','luna','🌙'],['M','Emme','mela','🍎'],['N','Enne','nuvola','☁️'],['O','O','orso','🐻'],['P','Pi','palla','⚽'],['Q','Cu','quadro','🖼️'],['R','Erre','rana','🐸'],['S','Esse','sole','☀️'],['T','Ti','treno','🚂'],['U','U','uva','🍇'],['V','Vi','violino','🎻'],['Z','Zeta','zebra','🦓']
            ]),
            interface:{
                pageTitle:'Toddler Arcade',allLanguages:'Tutte e 12',feedSanta:'Dai da mangiare a Babbo Natale',trucks:'Grandi veicoli',balloons:'Palloncini con i numeri',animals:'Animali',chooseGame:'Scegli un gioco',previousGame:'Gioco precedente',nextGame:'Gioco successivo',chooseLanguage:'Lingua',gamesLabel:'Giochi',menuLabel:'Menu dei giochi',playNow:'Gioca ora',swipeForGames:'Scorri per altri giochi',hideControls:'Nascondi i comandi',showControls:'Giochi e lingue',randomGame:'Gioco a sorpresa',randomLanguageGame:'Gioco e lingua a sorpresa',playTimer:'Imposta il tempo di gioco',playTimerTitle:'Tempo di gioco',playTimerPrompt:'Per quanto tempo giochiamo?',minutesShort:'min',noTimer:'Nessun timer',cancel:'Annulla',timeUpTitle:'Abbiamo finito!',timeUpMessage:'Hai giocato benissimo. Facciamo una pausa!',moreTime:'Adulto: aggiungi tempo',
                santaPrompt:'Ari cosa diamo da mangiare a Babbo Natale? 🎅',morePlease:'Cosa mangerà adesso Babbo Natale Ari? 🎅',tickle:'Oh oh oh! Mi fai il solletico Ari! 😆',santaLaugh:'Oh! Oh! Oh!',dragFood:'Trascina o tocca il cibo',popBalloons:'Scoppia i palloncini! 🎈',popped:n=>`Hai scoppiato il palloncino numero ${n}! ⭐`,balloonLevelUp:n=>`Bravissimo! Ora da 1 a ${n}! 🚀`,santaLabel:'Babbo Natale',
                everyday:'Oggetti di ogni giorno',letters:'Giardino delle lettere',shapes:'Colori e forme',counting:'Conta e scegli',body:'Il corpo',runner:'Prendi il broccolo',music:'Studio musicale',beat:'Copia la sequenza',dance:'Balla e fermati',bells:'Campanelle di Babbo Natale',everydayPrompt:'Scopri sei oggetti alla volta',everydayExplore:'👀 Scopri',everydayFind:'👆 Tocca',everydayMore:'Altri oggetti →',findQuestion:item=>`Tocca ${item}`,findTry:'Guarda ancora',findFound:()=>`È questo!`,findNext:'▶ Il prossimo',findReal:()=>`Riesci a trovarne uno vicino a te?`,
                letterPrompt:'Tocca una lettera',letterPhrase:item=>`${item.name}. ${item.letter} come ${item.word}.`,shapePrompt:(color,shape)=>`Tocca. Colore ${color}. Forma ${shape}.`,shapeTry:'Guarda ancora',shapeGreat:'L’hai trovato!',countPrompt:'Quanti sono?',countTry:'Conta ancora',countGreat:n=>`${n}! Ottimo!`,bodyPrompt:'Tocca una parte del corpo',bodyHint:'Tocca il personaggio',runnerPrompt:'Tieni premuto per volare · Lascia per scendere',runnerHint:'Tieni premuto per volare',runnerRotate:'Gira il telefono di lato',runnerTutorial:'Tieni premuto per volare · Lascia per scendere',runnerCaught:(food,score)=>`${food}! ${score === 1 ? 'Un punto' : `${score} punti`}!`,runnerOw:'Ahi!',
                musicPrompt:'Fai musica',musicTogether:'Suonate a turno',beatPrompt:'Guarda la sequenza',beatStart:'Tocca l’orsetto che balla',beatNext:'▶ Nuova sequenza',beatReady:'Pronto? Tocca l’orsetto che balla.',beatExplain:'Guarda la sequenza. Poi ripetila. Pronto?',beatYourTurn:'Tocca a te!',beatGreat:'Te la sei ricordata!',beatPraise:['Bravissimo!','Molto bene!','Ce l’hai fatta!','Fantastico!'],beatAgain:'Guarda di nuovo la stessa sequenza',danceReady:'Pronto?',danceStart:'▶ Balla',danceStop:'■ Stop',danceTogether:'Fate spazio e ballate insieme',bellsPrompt:'Suona con Babbo Natale',bellsSantaAction:'Ascolta Babbo Natale',bellsBellAction:'Suona la campana grande',jingleStart:'🎶 Suona Jingle Bells',jingleStop:'■ Ferma la canzone'
            },
            settings:{button:'Impostazioni genitore',title:'Impostazioni genitore',greekNames:'🇬🇷 Nomi in greco',otherNames:'🌍 Nomi nelle altre lingue',help:'Separa i soprannomi con virgole. Mantieni lo stesso ordine nelle due liste.',required:'Inserisci almeno un nome.',error:'Le due liste devono avere lo stesso numero di nomi.',close:'Chiudi',cancel:'Annulla',save:'Salva',restore:'Ripristina predefiniti',setup:'🌍 Lingue e configurazione',diceTitle:'🎲 Cosa fa il dado?',diceSingle:'Una lingua',diceMultilingual:'Tutte le lingue',diceRandom:'Lingua casuale',timer:'Tempo di gioco',soundCredits:'🔊 Fonti dei suoni reali'},
            onboarding:{step:n=>`Passaggio ${n} di 3`,primaryTitle:'Qual è la lingua principale del gioco?',primaryLead:'Apparirà per prima e verrà usata nei menu.',languagesTitle:'Quali lingue vuoi che ascolti il tuo bambino?',languagesLead:'Aggiungi le altre lingue che vuoi. Potrai cambiarle dopo.',languageMain:'Principale',languageCount:n=>`${n} lingue attive`,addLanguage:'+ Aggiungi una lingua',allLanguagesAdded:'Tutte le lingue sono state aggiunte',localeHint:'✨ Preselezionata dalla lingua e dalla regione del dispositivo',namesTitle:'Come deve chiamare il bambino il gioco?',namesLead:'Facoltativo: inserisci i nomi come vuoi sentirli o salta questo passaggio.',greekLabel:'🇬🇷 In greco',otherLabel:'🌍 Nelle altre lingue',namesHelp:'Facoltativo. Separa nome e soprannomi con virgole.',back:'Indietro',next:'Continua',finish:'Salva e gioca',skipNames:'Salta per ora',close:'Chiudi',required:'Inserisci almeno un nome.',mismatch:'Le due liste devono avere lo stesso numero di nomi.'},
            danceMoves:['Balla!','Batti le mani!','Corri in cerchio!','Salta!','Gira!','Mani in alto!'],freeze:'Fermo!',leader:'Tocca a te!',
            santaThanks:(food,foodName,name,variant)=>[
                `${food}! Grazie per ${foodName} ${name}!`,`${food}! Era delizioso! Grazie ${name}!`,`${food}! Mi è piaciuto! Grazie ${name}!`
            ][variant]
        },
        tr: {
            code:'tr-TR', flag:'🇹🇷', picker:'🇹🇷 Türkiye — Türkçe',
            foods:['Elma','Muz','Pizza','Havuç','Dondurma','Çilek','Kurabiye','Karpuz','Brokoli','Üzüm','Portakal','Armut','Ananas','Avokado','Mısır','Tako','Ekmek','Peynir','Yumurta','Süt','Domates','Patates','Kiraz','Şeftali','Mango','Limon','Sosisli sandviç'],
            santaFoods:['elma','muz','pizza','havuç','dondurma','çilek','kurabiye','karpuz','brokoli','üzüm','portakal','armut','ananas','avokado','mısır','tako','ekmek','peynir','yumurta','süt','domates','patates','kiraz','şeftali','mango','limon','sosisli sandviç'],
            trucks:['Traktör','Vinç','Ekskavatör','Damperli kamyon','İtfaiye aracı','Buldozer','Ambulans','Roket','Kazıcı yükleyici','Yükleyici','Yol silindiri','Beton mikseri','Çöp kamyonu','Çekici','Kar küreme aracı','Forklift','Mini yükleyici','Asfalt serme makinesi','Sondaj makinesi','Canavar kamyon','Polis arabası','Okul otobüsü','Dağıtım aracı','Tren'],
            animals:['Köpek','Kedi','Aslan','İnek','Kurbağa','Ördek','Koyun','Domuzcuk','At','Fil','Maymun','Kaplan','Ayıcık','Tavşan','Tavuk','Horoz','Keçi','Eşek','Baykuş','Penguen','Zürafa','Zebra','Timsah','Balina'],
            numbers:['Bir','İki','Üç','Dört','Beş','Altı','Yedi','Sekiz','Dokuz','On','On bir','On iki','On üç','On dört','On beş','On altı','On yedi','On sekiz','On dokuz','Yirmi'],
            everyday:['Pipet','Süt bardağı','Tabak','Kase','Kaşık','Çatal','Peçete','Biberon','Tava','Tencere','Buz küpü','Sandalye','Diş fırçası','Sabun','Çorap','Ayakkabı','Yatak','Küvet','Kapı','Anahtarlar'],
            everydayPrompts:['pipeti','süt bardağını','tabağı','kaseyi','kaşığı','çatalı','peçeteyi','biberonu','tavayı','tencereyi','buz küpünü','sandalyeyi','diş fırçasını','sabunu','çorabı','ayakkabıyı','yatağı','küveti','kapıyı','anahtarları'],
            instruments:['Davul seti','Gitar','Klavye','Çanlar','Marakas','El davulu','Trompet','Mikrofon','Keman','Saksofon','Flüt','Akordeon','Banjo'],
            colors:['kırmızı','mavi','sarı','yeşil'],shapes:['daire','kare','üçgen','yıldız','kalp'],
            body:['Baş','Kulaklar','Gözler','Burun','Ağız','Karın','Kol','El · Parmaklar','Parmaklar','Diz','Bacak','Ayak · Ayak parmakları','Ayak parmakları'],
            runnerFoods:['Brokoli','Domates','Havuç','Elma','Muz','Çilek','Portakal','Mısır','Armut','Üzüm','Karpuz','Ananas','Avokado','Kiraz','Limon','Patates','Şeftali','Mango','Dolmalık biber','Salatalık','Patlıcan','Tatlı patates','Kivi','Yaban mersini'],bellNotes:['Do','Re','Mi','Fa','Sol'],
            letters:letterSet([
                ['A','A','araba','🚗'],['B','Be','balon','🎈'],['C','Ce','ceviz','🌰'],['Ç','Çe','çilek','🍓'],['D','De','dinozor','🦖'],['E','E','elma','🍎'],['F','Fe','fil','🐘'],['G','Ge','gitar','🎸'],['Ğ','Yumuşak ge','yağmur','🌧️'],['H','He','havuç','🥕'],['I','I','ıspanak','🥬'],['İ','İ','inek','🐮'],['J','Je','jet','✈️'],['K','Ke','kedi','🐱'],['L','Le','limon','🍋'],['M','Me','muz','🍌'],['N','Ne','nar','🍎'],['O','O','otobüs','🚌'],['Ö','Ö','ördek','🦆'],['P','Pe','penguen','🐧'],['R','Re','roket','🚀'],['S','Se','su','💧'],['Ş','Şe','şapka','🧢'],['T','Te','tren','🚂'],['U','U','uçak','✈️'],['Ü','Ü','üzüm','🍇'],['V','Ve','vişne','🍒'],['Y','Ye','yıldız','⭐'],['Z','Ze','zebra','🦓']
            ]),
            interface:{
                pageTitle:'Toddler Arcade',allLanguages:'12 dilin tümü',feedSanta:'Noel Baba’yı besle',trucks:'Büyük araçlar',balloons:'Sayı balonları',animals:'Hayvanlar',chooseGame:'Bir oyun seç',previousGame:'Önceki oyun',nextGame:'Sonraki oyun',chooseLanguage:'Dil',gamesLabel:'Oyunlar',menuLabel:'Oyun menüsü',playNow:'Şimdi oyna',swipeForGames:'Daha fazla oyun için kaydır',hideControls:'Kontrolleri gizle',showControls:'Oyunlar ve diller',randomGame:'Sürpriz oyun',randomLanguageGame:'Sürpriz oyun ve dil',playTimer:'Oyun süresini ayarla',playTimerTitle:'Oyun süresi',playTimerPrompt:'Ne kadar oynayalım?',minutesShort:'dk',noTimer:'Süre sınırı yok',cancel:'İptal',timeUpTitle:'Bitti!',timeUpMessage:'Harika oynadın. Şimdi mola zamanı!',moreTime:'Yetişkin: süre ekle',
                santaPrompt:'Ari Noel Baba’ya ne yedirelim? 🎅',morePlease:'Noel Baba şimdi ne yesin Ari? 🎅',tickle:'Ho ho ho! Gıdıklanıyorum Ari! 😆',santaLaugh:'Ho! Ho! Ho!',dragFood:'Yemeği sürükle veya dokun',popBalloons:'Balonları patlat! 🎈',popped:n=>`${n} numaralı balon patladı! ⭐`,balloonLevelUp:n=>`Harika! Şimdi 1’den ${n}’ye kadar! 🚀`,santaLabel:'Noel Baba',
                everyday:'Günlük eşyalar',letters:'Harf bahçesi',shapes:'Renkler ve şekiller',counting:'Say ve seç',body:'Vücudumuz',runner:'Brokoliyi yakala',music:'Müzik stüdyosu',beat:'Ritmi kopyala',dance:'Dans et ve don',bells:'Noel Baba’nın çanları',everydayPrompt:'Altı eşyayı keşfet',everydayExplore:'👀 Keşfet',everydayFind:'👆 Dokun',everydayMore:'Başka eşyalar →',findQuestion:item=>`Şuna dokun: ${item}`,findTry:'Bir daha bak',findFound:()=>`İşte bu!`,findNext:'▶ Sonraki',findReal:()=>`Yakınında buna benzeyen bir şey bulabilir misin?`,
                letterPrompt:'Bir harfe dokun',letterPhrase:item=>`${item.name}. ${item.word} kelimesinde ${item.letter}.`,shapePrompt:(color,shape)=>`Dokun. Renk ${color}. Şekil ${shape}.`,shapeTry:'Bir daha bak',shapeGreat:'Buldun!',countPrompt:'Kaç tane?',countTry:'Bir daha say',countGreat:n=>`${n}! Çok güzel saydın!`,bodyPrompt:'Bir vücut bölümüne dokun',bodyHint:'Karaktere dokun',runnerPrompt:'Uçmak için basılı tut · İnmek için bırak',runnerHint:'Uçmak için basılı tut',runnerRotate:'Telefonu yan çevir',runnerTutorial:'Uçmak için basılı tut · İnmek için bırak',runnerCaught:(food,score)=>`${food}! ${score} puan!`,runnerOw:'Ah!',
                musicPrompt:'Müzik yap',musicTogether:'Sırayla çalın',beatPrompt:'Ritmi izle',beatStart:'Dans eden ayıcığa dokun',beatNext:'▶ Yeni ritim',beatReady:'Hazır mısın? Dans eden ayıcığa dokun.',beatExplain:'Ritmi izle. Sonra aynısını çal. Hazır mısın?',beatYourTurn:'Şimdi sıra sende!',beatGreat:'Hatırladın!',beatPraise:['Harika!','Çok güzel!','Başardın!','Süpersin!'],beatAgain:'Aynı ritmi bir daha izle',danceReady:'Hazır mısın?',danceStart:'▶ Dans et',danceStop:'■ Dur',danceTogether:'Yer açın ve birlikte dans edin',bellsPrompt:'Noel Baba’yla çal',bellsSantaAction:'Noel Baba’yı dinle',bellsBellAction:'Büyük çanı çal',jingleStart:'🎶 Jingle Bells’i çal',jingleStop:'■ Şarkıyı durdur'
            },
            settings:{button:'Ebeveyn ayarları',title:'Ebeveyn ayarları',greekNames:'🇬🇷 Yunanca isimler',otherNames:'🌍 Diğer dillerdeki isimler',help:'Takma adları virgülle ayır. İki listede de aynı sırayı kullan.',required:'En az bir isim gir.',error:'İki listede aynı sayıda isim olmalı.',close:'Kapat',cancel:'İptal',save:'Kaydet',restore:'Varsayılanları geri yükle',setup:'🌍 Diller ve kurulum',diceTitle:'🎲 Zar ne yapsın?',diceSingle:'Tek dil',diceMultilingual:'Tüm diller',diceRandom:'Rastgele dil',timer:'Oyun süresi',soundCredits:'🔊 Gerçek ses kaynakları'},
            onboarding:{step:n=>`3 adımın ${n}. adımı`,primaryTitle:'Oyunun ana dili hangisi?',primaryLead:'İlk sırada görünür ve menülerde kullanılır.',languagesTitle:'Çocuğun hangi dilleri duysun?',languagesLead:'İstediğin diğer dilleri ekle. Daha sonra değiştirebilirsin.',languageMain:'Ana dil',languageCount:n=>`${n} dil açık`,addLanguage:'+ Başka dil ekle',allLanguagesAdded:'Tüm diller eklendi',localeHint:'✨ Cihaz diline ve bölgesine göre seçildi',namesTitle:'Oyun çocuğuna nasıl seslensin?',namesLead:'İsteğe bağlı: isimleri duyulmasını istediğin gibi yaz veya bu adımı atla.',greekLabel:'🇬🇷 Yunanca',otherLabel:'🌍 Diğer dillerde',namesHelp:'İsteğe bağlı. İsim ve takma adları virgülle ayır.',back:'Geri',next:'Devam',finish:'Kaydet ve oyna',skipNames:'Şimdilik atla',close:'Kapat',required:'En az bir isim gir.',mismatch:'İki listede aynı sayıda isim olmalı.'},
            danceMoves:['Dans et!','Alkışla!','Daire çizerek koş!','Zıpla!','Dön!','Eller yukarı!'],freeze:'Don!',leader:'Şimdi sıra sende!',
            santaThanks:(food,foodName,name,variant)=>[`${food}! ${foodName} için teşekkürler ${name}!`,`${food}! Çok lezzetliydi! Teşekkürler ${name}!`,`${food}! Çok beğendim! Teşekkürler ${name}!`][variant]
        },
        ptBR: {
            code:'pt-BR', flag:'🇧🇷', picker:'🇧🇷 Brasil — Português',
            foods:['Maçã','Banana','Pizza','Cenoura','Sorvete','Morango','Biscoito','Melancia','Brócolis','Uvas','Laranja','Pera','Abacaxi','Abacate','Milho','Taco','Pão','Queijo','Ovo','Leite','Tomate','Batata','Cerejas','Pêssego','Manga','Limão','Cachorro-quente'],
            santaFoods:['a maçã','a banana','a pizza','a cenoura','o sorvete','o morango','o biscoito','a melancia','o brócolis','as uvas','a laranja','a pera','o abacaxi','o abacate','o milho','o taco','o pão','o queijo','o ovo','o leite','o tomate','a batata','as cerejas','o pêssego','a manga','o limão','o cachorro-quente'],
            trucks:['Trator','Guindaste','Escavadeira','Caminhão basculante','Caminhão de bombeiros','Trator de esteira','Ambulância','Foguete','Retroescavadeira','Pá carregadeira','Rolo compressor','Betoneira','Caminhão de lixo','Guincho','Limpa-neve','Empilhadeira','Minicarregadeira','Pavimentadora','Perfuratriz','Caminhão monstro','Carro de polícia','Ônibus escolar','Van de entrega','Trem'],
            animals:['Cachorrinho','Gatinho','Leãozinho','Vaquinha','Sapinho','Patinho','Ovelhinha','Porquinho','Cavalinho','Elefantinho','Macaquinho','Tigrinho','Ursinho','Coelhinho','Galinha','Galo','Cabritinho','Burrinho','Coruja','Pinguim','Girafa','Zebra','Crocodilo','Baleia']
            ,numbers:['Um','Dois','Três','Quatro','Cinco','Seis','Sete','Oito','Nove','Dez','Onze','Doze','Treze','Catorze','Quinze','Dezesseis','Dezessete','Dezoito','Dezenove','Vinte']
            ,everyday:['Canudo','Copo de leite','Prato','Tigela','Colher','Garfo','Guardanapo','Mamadeira','Frigideira','Panela','Cubo de gelo','Cadeira','Escova de dentes','Sabonete','Meia','Sapato','Cama','Banheira','Porta','Chaves']
            ,everydayPrompts:['o canudo','o copo de leite','o prato','a tigela','a colher','o garfo','o guardanapo','a mamadeira','a frigideira','a panela','o cubo de gelo','a cadeira','a escova de dentes','o sabonete','a meia','o sapato','a cama','a banheira','a porta','as chaves']
            ,instruments:['Bateria','Violão','Teclado','Sinos','Maracas','Tambor de mão','Trompete','Microfone','Violino','Saxofone','Flauta','Acordeão','Banjo']
            ,colors:['vermelho','azul','amarelo','verde']
            ,shapes:['círculo','quadrado','triângulo','estrela','coração']
            ,body:['Cabeça','Orelhas','Olhos','Nariz','Boca','Barriga','Braço','Mão · Dedos','Dedos','Joelho','Perna','Pé · Dedos do pé','Dedos do pé']
            ,runnerFoods:['Brócolis','Tomate','Cenoura','Maçã','Banana','Morango','Laranja','Milho','Pera','Uvas','Melancia','Abacaxi','Abacate','Cerejas','Limão','Batata','Pêssego','Manga','Pimentão','Pepino','Berinjela','Batata-doce','Kiwi','Mirtilos']
            ,bellNotes:['Dó','Ré','Mi','Fá','Sol']
            ,letters:letterSet([
                ['A','A','abelha','🐝'],['B','Bê','bola','⚽'],['C','Cê','cachorro','🐶'],['D','Dê','dinossauro','🦖'],['E','E','elefante','🐘'],['F','Efe','flor','🌸'],['G','Gê','gato','🐱'],['H','Agá','helicóptero','🚁'],['I','I','ilha','🏝️'],['J','Jota','jacaré','🐊'],['K','Cá','kiwi','🥝'],['L','Ele','lua','🌙'],['M','Eme','maçã','🍎'],['N','Ene','nuvem','☁️'],['O','O','ovelha','🐑'],['P','Pê','pato','🦆'],['Q','Quê','queijo','🧀'],['R','Erre','robô','🤖'],['S','Esse','sol','☀️'],['T','Tê','trem','🚂'],['U','U','uva','🍇'],['V','Vê','violino','🎻'],['W','Dáblio','waffle','🧇'],['X','Xis','xilofone','🎶'],['Y','Ípsilon','yoga','🧘'],['Z','Zê','zebra','🦓']
            ])
            ,interface:{
                pageTitle:'Toddler Arcade',allLanguages:'Todos os 12',feedSanta:'Alimente o Papai Noel',trucks:'Veículos grandes',balloons:'Balões com números',animals:'Animais',chooseGame:'Escolha um jogo',previousGame:'Jogo anterior',nextGame:'Próximo jogo',chooseLanguage:'Idioma',gamesLabel:'Jogos',menuLabel:'Menu de jogos',playNow:'Jogar agora',swipeForGames:'Deslize para ver mais jogos',hideControls:'Ocultar controles',showControls:'Jogos e idiomas',randomGame:'Jogo surpresa',randomLanguageGame:'Jogo e idioma surpresa',playTimer:'Definir tempo de jogo',playTimerTitle:'Tempo de jogo',playTimerPrompt:'Por quanto tempo vamos jogar?',minutesShort:'min',noTimer:'Sem timer',cancel:'Cancelar',timeUpTitle:'Terminamos!',timeUpMessage:'Você jogou muito bem. Hora de descansar!',moreTime:'Adulto: adicionar tempo',
                santaPrompt:'Ari o que vamos dar para o Papai Noel? 🎅',morePlease:'O que o Papai Noel vai comer agora Ari? 🎅',tickle:'Ho ho ho! Isso faz cócegas Ari! 😆',santaLaugh:'Ho! Ho! Ho!',dragFood:'Arraste ou toque na comida',popBalloons:'Estoure os balões! 🎈',popped:n=>`Você estourou o balão número ${n}! ⭐`,balloonLevelUp:n=>`Muito bem! Agora de 1 até ${n}! 🚀`,santaLabel:'Papai Noel',
                everyday:'Coisas do dia a dia',letters:'Jardim das letras',shapes:'Cores e formas',counting:'Conte e escolha',body:'O corpo',runner:'Pegue o brócolis',music:'Estúdio de música',beat:'Copie o ritmo',dance:'Dance e congele',bells:'Sinos do Papai Noel',everydayPrompt:'Explore seis coisas de cada vez',everydayExplore:'👀 Explorar',everydayFind:'👆 Toque',everydayMore:'Mais coisas →',findQuestion:item=>`Toque em ${item}`,findTry:'Olhe de novo',findFound:()=>`É esse!`,findNext:'▶ Próximo',findReal:()=>`Você consegue achar um igual perto de você?`,
                letterPrompt:'Toque em uma letra',letterPhrase:item=>`${item.name}. ${item.letter} de ${item.word}.`,shapePrompt:(color,shape)=>`Toque. Cor ${color}. Forma ${shape}.`,shapeTry:'Olhe de novo',shapeGreat:'Você achou!',countPrompt:'Quantos?',countTry:'Conte de novo',countGreat:n=>`${n}! Contou muito bem!`,bodyPrompt:'Toque em uma parte do corpo',bodyHint:'Toque no personagem',runnerPrompt:'Segure para voar · Solte para descer',runnerHint:'Segure para voar',runnerRotate:'Vire o celular de lado',runnerTutorial:'Segure para voar · Solte para descer',runnerCaught:(food,score)=>`${food}! ${score === 1 ? 'Um ponto' : `${score} pontos`}!`,runnerOw:'Ai!',
                musicPrompt:'Faça música',musicTogether:'Toquem um de cada vez',beatPrompt:'Veja o ritmo',beatStart:'Toque no ursinho que dança',beatNext:'▶ Novo ritmo',beatReady:'Pronto para brincar? Toque no ursinho que dança.',beatExplain:'Veja o ritmo. Depois repita. Pronto?',beatYourTurn:'Sua vez!',beatGreat:'Você lembrou!',beatPraise:['Muito bem!','Parabéns!','Você conseguiu!','Incrível!'],beatAgain:'Veja o mesmo ritmo de novo',danceReady:'Pronto?',danceStart:'▶ Dançar',danceStop:'■ Parar',danceTogether:'Abram espaço e dancem juntos',bellsPrompt:'Toque com o Papai Noel',bellsSantaAction:'Ouça o Papai Noel',bellsBellAction:'Toque o sino grande',jingleStart:'🎶 Tocar Jingle Bells',jingleStop:'■ Parar a música'
            }
            ,settings:{button:'Configurações dos pais',title:'Configurações dos pais',greekNames:'🇬🇷 Nomes em grego',otherNames:'🌍 Nomes nos outros idiomas',help:'Separe os apelidos com vírgulas. Mantenha a mesma ordem nas duas listas.',required:'Digite pelo menos um nome.',error:'As duas listas precisam ter a mesma quantidade de nomes.',close:'Fechar',cancel:'Cancelar',save:'Salvar',restore:'Restaurar padrões',setup:'🌍 Idiomas e configuração',diceTitle:'🎲 O que o dado faz?',diceSingle:'Um idioma',diceMultilingual:'Todos os idiomas',diceRandom:'Idioma aleatório',timer:'Tempo de jogo',soundCredits:'🔊 Créditos dos sons reais'}
            ,onboarding:{step:n=>`Etapa ${n} de 3`,primaryTitle:'Qual é o idioma principal do jogo?',primaryLead:'Ele aparecerá primeiro e será usado nos menus.',languagesTitle:'Quais idiomas você quer que seu filho ouça?',languagesLead:'Adicione os outros idiomas que quiser. Você poderá mudar depois.',languageMain:'Principal',languageCount:n=>`${n} idiomas ativos`,addLanguage:'+ Adicionar outro idioma',allLanguagesAdded:'Todos os idiomas adicionados',localeHint:'✨ Pré-selecionado pelo idioma e região do dispositivo',namesTitle:'Como o jogo deve chamar seu filho?',namesLead:'Opcional: escreva os nomes como quer que sejam falados ou pule esta etapa.',greekLabel:'🇬🇷 Em grego',otherLabel:'🌍 Nos outros idiomas',namesHelp:'Opcional. Separe o nome e os apelidos com vírgulas.',back:'Voltar',next:'Continuar',finish:'Salvar e jogar',skipNames:'Pular por enquanto',close:'Fechar',required:'Digite pelo menos um nome.',mismatch:'As duas listas precisam ter a mesma quantidade de nomes.'}
            ,danceMoves:['Dance!','Bata palmas!','Corra em círculos!','Pule!','Gire!','Mãos para cima!']
            ,freeze:'Congelou!'
            ,leader:'Sua vez!'
            ,santaThanks:(food,foodName,name,variant)=>[`${food}! Obrigado por ${foodName} ${name}!`,`${food}! Estava uma delícia! Obrigado ${name}!`,`${food}! Eu adorei! Obrigado ${name}!`][variant]
        },
        nl: {
            code:'nl-NL',flag:'🇳🇱',picker:'🇳🇱 Nederland — Nederlands',
            foods:['Appel','Banaan','Pizza','Wortel','IJsje','Aardbei','Koekje','Watermeloen','Broccoli','Druiven','Sinaasappel','Peer','Ananas','Avocado','Maïs','Taco','Brood','Kaas','Ei','Melk','Tomaat','Aardappel','Kersen','Perzik','Mango','Citroen','Hotdog'],
            santaFoods:['de appel','de banaan','de pizza','de wortel','het ijsje','de aardbei','het koekje','de watermeloen','de broccoli','de druiven','de sinaasappel','de peer','de ananas','de avocado','de maïs','de taco','het brood','de kaas','het ei','de melk','de tomaat','de aardappel','de kersen','de perzik','de mango','de citroen','de hotdog'],
            trucks:['Tractor','Kraan','Graafmachine','Kiepwagen','Brandweerwagen','Bulldozer','Ambulance','Raket','Graaflaadmachine','Wiellader','Wals','Betonmixer','Vuilniswagen','Takelwagen','Sneeuwploeg','Vorkheftruck','Schranklader','Asfaltmachine','Boorinstallatie','Monstertruck','Politieauto','Schoolbus','Bestelbus','Trein'],
            animals:['Hondje','Katje','Leeuw','Koe','Kikker','Eendje','Schaap','Varkentje','Paard','Olifant','Aapje','Tijger','Beertje','Konijntje','Kip','Haan','Geit','Ezel','Uil','Pinguïn','Giraf','Zebra','Krokodil','Walvis'],
            numbers:['Eén','Twee','Drie','Vier','Vijf','Zes','Zeven','Acht','Negen','Tien','Elf','Twaalf','Dertien','Veertien','Vijftien','Zestien','Zeventien','Achttien','Negentien','Twintig'],
            everyday:['Rietje','Glas melk','Bord','Kom','Lepel','Vork','Servet','Babyfles','Koekenpan','Pan','IJsblokje','Stoel','Tandenborstel','Zeep','Sok','Schoen','Bed','Bad','Deur','Sleutels'],
            everydayPrompts:['het rietje','het glas melk','het bord','de kom','de lepel','de vork','het servet','de babyfles','de koekenpan','de pan','het ijsblokje','de stoel','de tandenborstel','de zeep','de sok','de schoen','het bed','het bad','de deur','de sleutels'],
            instruments:['Drumstel','Gitaar','Keyboard','Bellen','Maracas','Handtrommel','Trompet','Microfoon','Viool','Saxofoon','Fluit','Accordeon','Banjo'],
            colors:['rood','blauw','geel','groen'],shapes:['cirkel','vierkant','driehoek','ster','hart'],
            body:['Hoofd','Oren','Ogen','Neus','Mond','Buik','Arm','Hand · Vingers','Vingers','Knie','Been','Voet · Tenen','Tenen'],runnerFoods:['Broccoli','Tomaat','Wortel','Appel','Banaan','Aardbei','Sinaasappel','Maïs','Peer','Druiven','Watermeloen','Ananas','Avocado','Kersen','Citroen','Aardappel','Perzik','Mango','Paprika','Komkommer','Aubergine','Zoete aardappel','Kiwi','Blauwe bessen'],bellNotes:['C','D','E','F','G'],
            letters:letterSet([
                ['A','A','appel','🍎'],['B','Bee','bal','⚽'],['C','Cee','clown','🤡'],['D','Dee','dino','🦖'],['E','E','eend','🦆'],['F','Ef','fiets','🚲'],['G','Gee','gitaar','🎸'],['H','Haa','huis','🏠'],['I','Ie','ijsje','🍦'],['J','Jee','jas','🧥'],['K','Kaa','kat','🐱'],['L','El','leeuw','🦁'],['M','Em','maan','🌙'],['N','En','nest','🪺'],['O','O','olifant','🐘'],['P','Pee','peer','🍐'],['Q','Kuu','quiz','❓'],['R','Er','regenboog','🌈'],['S','Es','ster','⭐'],['T','Tee','trein','🚂'],['U','U','uil','🦉'],['V','Vee','vis','🐟'],['W','Wee','walvis','🐋'],['X','Iks','xylofoon','🎶'],['Y','Ypsilon','yoghurt','🥣'],['Z','Zet','zebra','🦓']
            ])
            ,interface:{
                pageTitle:'Toddler Arcade',allLanguages:'Alle 12',feedSanta:'Geef de kerstman eten',trucks:'Grote voertuigen',balloons:'Cijferballonnen',animals:'Dieren',chooseGame:'Kies een spel',previousGame:'Vorig spel',nextGame:'Volgend spel',chooseLanguage:'Taal',gamesLabel:'Spellen',menuLabel:'Spelmenu',playNow:'Nu spelen',swipeForGames:'Veeg voor meer spellen',hideControls:'Bediening verbergen',showControls:'Spellen en talen',randomGame:'Verrassingsspel',randomLanguageGame:'Verrassingsspel en taal',playTimer:'Speeltijd instellen',playTimerTitle:'Speeltijd',playTimerPrompt:'Hoe lang gaan we spelen?',minutesShort:'min',noTimer:'Geen timer',cancel:'Annuleren',timeUpTitle:'Klaar!',timeUpMessage:'Goed gespeeld. Tijd voor een pauze!',moreTime:'Volwassene: meer tijd',
                santaPrompt:'Ari wat geven we de kerstman te eten? 🎅',morePlease:'Wat zal de kerstman nu eten Ari? 🎅',tickle:'Ho ho ho! Dat kriebelt Ari! 😆',santaLaugh:'Ho! Ho! Ho!',dragFood:'Sleep of tik op eten',popBalloons:'Laat de ballonnen knallen! 🎈',popped:n=>`Ballon nummer ${n} is geknald! ⭐`,balloonLevelUp:n=>`Geweldig! Nu van 1 tot ${n}! 🚀`,santaLabel:'Kerstman',
                everyday:'Dagelijkse dingen',letters:'Lettertuin',shapes:'Kleuren en vormen',counting:'Tel en kies',body:'Het lichaam',runner:'Vang de broccoli',music:'Muziekstudio',beat:'Doe het patroon na',dance:'Dans en stop',bells:'Kerstbellen',everydayPrompt:'Ontdek zes dingen tegelijk',everydayExplore:'👀 Ontdek',everydayFind:'👆 Tik',everydayMore:'Meer dingen →',findQuestion:item=>`Tik op ${item}`,findTry:'Kijk nog eens',findFound:()=>`Dat is hem!`,findNext:'▶ Volgende',findReal:()=>`Kun je zoiets bij jou in de buurt vinden?`,
                letterPrompt:'Tik op een letter',letterPhrase:item=>`${item.name}. ${item.letter} van ${item.word}.`,shapePrompt:(color,shape)=>`Tik. Kleur ${color}. Vorm ${shape}.`,shapeTry:'Kijk nog eens',shapeGreat:'Je hebt hem gevonden!',countPrompt:'Hoeveel?',countTry:'Tel nog eens',countGreat:n=>`${n}! Goed geteld!`,bodyPrompt:'Tik op een lichaamsdeel',bodyHint:'Tik op het figuurtje',runnerPrompt:'Houd vast om te vliegen · Laat los om te landen',runnerHint:'Houd vast om te vliegen',runnerRotate:'Draai de telefoon op zijn kant',runnerTutorial:'Houd vast om te vliegen · Laat los om te landen',runnerCaught:(food,score)=>`${food}! ${score === 1 ? 'Eén punt' : `${score} punten`}!`,runnerOw:'Au!',
                musicPrompt:'Maak muziek',musicTogether:'Speel om de beurt',beatPrompt:'Kijk naar het patroon',beatStart:'Tik op de dansende beer',beatNext:'▶ Nieuw patroon',beatReady:'Klaar om te spelen? Tik op de dansende beer.',beatExplain:'Kijk naar het patroon. Doe het daarna na. Klaar?',beatYourTurn:'Jij bent!',beatGreat:'Je hebt het onthouden!',beatPraise:['Heel goed!','Goed gedaan!','Gelukt!','Geweldig!'],beatAgain:'Kijk nog eens naar hetzelfde patroon',danceReady:'Klaar?',danceStart:'▶ Dansen',danceStop:'■ Stop',danceTogether:'Maak ruimte en dans samen',bellsPrompt:'Speel met de kerstman',bellsSantaAction:'Luister naar de kerstman',bellsBellAction:'Luid de grote bel',jingleStart:'🎶 Speel Jingle Bells',jingleStop:'■ Stop het liedje'
            }
            ,settings:{button:'Ouderinstellingen',title:'Ouderinstellingen',greekNames:'🇬🇷 Namen in het Grieks',otherNames:'🌍 Namen in de andere talen',help:'Scheid bijnamen met komma’s. Houd dezelfde volgorde in beide lijsten.',required:'Vul minstens één naam in.',error:'Beide lijsten moeten evenveel namen hebben.',close:'Sluiten',cancel:'Annuleren',save:'Opslaan',restore:'Standaard herstellen',setup:'🌍 Talen en installatie',diceTitle:'🎲 Wat doet de dobbelsteen?',diceSingle:'Eén taal',diceMultilingual:'Alle talen',diceRandom:'Willekeurige taal',timer:'Speeltijd',soundCredits:'🔊 Bronnen van echte geluiden'}
            ,onboarding:{step:n=>`Stap ${n} van 3`,primaryTitle:'Wat is de hoofdtaal van het spel?',primaryLead:'Die staat vooraan en wordt voor de menu’s gebruikt.',languagesTitle:'Welke talen moet je kind horen?',languagesLead:'Voeg andere talen toe. Je kunt ze later wijzigen.',languageMain:'Hoofdtaal',languageCount:n=>`${n} talen aan`,addLanguage:'+ Nog een taal',allLanguagesAdded:'Alle talen toegevoegd',localeHint:'✨ Vooraf gekozen op basis van apparaat en regio',namesTitle:'Hoe moet het spel je kind noemen?',namesLead:'Optioneel: voer namen in zoals je ze wilt horen of sla deze stap over.',greekLabel:'🇬🇷 In het Grieks',otherLabel:'🌍 In de andere talen',namesHelp:'Optioneel. Scheid naam en bijnamen met komma’s.',back:'Terug',next:'Doorgaan',finish:'Opslaan en spelen',skipNames:'Nu overslaan',close:'Sluiten',required:'Vul minstens één naam in.',mismatch:'Beide lijsten moeten evenveel namen hebben.'}
            ,danceMoves:['Dans!','Klap in je handen!','Ren in een rondje!','Spring!','Draai!','Handen omhoog!']
            ,freeze:'Stop!'
            ,leader:'Jij bent!'
            ,santaThanks:(food,foodName,name,variant)=>[`${food}! Dank je voor ${foodName} ${name}!`,`${food}! Dat was lekker! Dank je ${name}!`,`${food}! Ik vond het heerlijk! Dank je ${name}!`][variant]
        },
        pl: {
            code:'pl-PL', flag:'🇵🇱', picker:'🇵🇱 Polska — Polski',
            foods:['Jabłko','Banan','Pizza','Marchewka','Lody','Truskawka','Ciastko','Arbuz','Brokuł','Winogrona','Pomarańcza','Gruszka','Ananas','Awokado','Kukurydza','Taco','Chleb','Ser','Jajko','Mleko','Pomidor','Ziemniak','Wiśnie','Brzoskwinia','Mango','Cytryna','Hot dog'],
            santaFoods:['jabłko','banana','pizzę','marchewkę','lody','truskawkę','ciastko','arbuza','brokuł','winogrona','pomarańczę','gruszkę','ananasa','awokado','kukurydzę','taco','chleb','ser','jajko','mleko','pomidora','ziemniaka','wiśnie','brzoskwinię','mango','cytrynę','hot doga']
            ,trucks:['Traktor','Dźwig','Koparka','Wywrotka','Wóz strażacki','Buldożer','Karetka','Rakieta','Koparko-ładowarka','Ładowarka kołowa','Walec drogowy','Betoniarka','Śmieciarka','Laweta','Pług śnieżny','Wózek widłowy','Miniładowarka','Rozściełacz asfaltu','Wiertnica','Monster truck','Radiowóz','Autobus szkolny','Samochód dostawczy','Pociąg']
            ,animals:['Piesek','Kotek','Lew','Krówka','Żabka','Kaczuszka','Owieczka','Świnka','Konik','Słonik','Małpka','Tygrysek','Misiu','Króliczek','Kurka','Kogut','Kózka','Osiołek','Sowa','Pingwin','Żyrafa','Zebra','Krokodyl','Wieloryb']
            ,numbers:['Jeden','Dwa','Trzy','Cztery','Pięć','Sześć','Siedem','Osiem','Dziewięć','Dziesięć','Jedenaście','Dwanaście']
            ,everyday:['Słomka','Szklanka mleka','Talerz','Miska','Łyżka','Widelec','Serwetka','Butelka dla dziecka','Patelnia','Garnek','Kostka lodu','Krzesło','Szczoteczka do zębów','Mydło','Skarpetka','But','Łóżko','Wanna','Drzwi','Klucze']
            ,everydayPrompts:['słomkę','szklankę mleka','talerz','miskę','łyżkę','widelec','serwetkę','butelkę','patelnię','garnek','kostkę lodu','krzesło','szczoteczkę do zębów','mydło','skarpetkę','but','łóżko','wannę','drzwi','klucze']
            ,instruments:['Perkusja','Gitara','Keyboard','Dzwonki','Marakasy','Bębenek','Trąbka','Mikrofon','Skrzypce','Saksofon','Flet','Akordeon','Banjo']
            ,colors:['czerwony','niebieski','żółty','zielony']
            ,shapes:['koło','kwadrat','trójkąt','gwiazda','serce']
            ,body:['Głowa','Uszy','Oczy','Nos','Usta','Brzuch','Ramię','Dłoń · Palce','Palce','Kolano','Noga','Stopa · Palce u stóp','Palce u stóp']
            ,runnerFoods:['Brokuł','Pomidor','Marchewka','Jabłko','Banan','Truskawka','Pomarańcza','Kukurydza','Gruszka','Winogrona','Arbuz','Ananas','Awokado','Wiśnie','Cytryna','Ziemniak','Brzoskwinia','Mango','Papryka','Ogórek','Bakłażan','Batat','Kiwi','Borówki']
            ,bellNotes:['C','D','E','F','G']
        },
    };

    window.extraLanguagePacks.pl.numbers.push(
        'Trzynaście','Czternaście','Piętnaście','Szesnaście',
        'Siedemnaście','Osiemnaście','Dziewiętnaście','Dwadzieścia'
    );
    window.extraLanguagePacks.pl.letters = letterSet([
        ['A','A','arbuz','🍉'],['Ą','A nosowe','wąż','🐍'],['B','Be','balon','🎈'],['C','Ce','cytryna','🍋'],
        ['Ć','Cie','ćma','🦋'],['D','De','dom','🏠'],['E','E','ekran','📺'],['Ę','E nosowe','gęś','🪿'],
        ['F','Ef','foka','🦭'],['G','Gie','gitara','🎸'],['H','Ha','hamak','🏝️'],['I','I','igła','🪡'],
        ['J','Jot','jabłko','🍎'],['K','Ka','kot','🐱'],['L','El','lew','🦁'],['Ł','Eł','łódka','⛵'],
        ['M','Em','miś','🧸'],['N','En','nos','👃'],['Ń','Eń','koń','🐴'],['O','O','oko','👁️'],
        ['Ó','U kreskowane','królik','🐰'],['P','Pe','pies','🐶'],['R','Er','ryba','🐟'],['S','Es','słońce','☀️'],
        ['Ś','Eś','ślimak','🐌'],['T','Te','traktor','🚜'],['U','U','ul','🐝'],['W','Wu','woda','💧'],
        ['Y','Y','dynia','🎃'],['Z','Zet','zebra','🦓'],['Ź','Ziet','źrebak','🐴'],['Ż','Żet','żaba','🐸']
    ]);
    Object.assign(window.extraLanguagePacks.pl, {
        interface:{
            pageTitle:'Toddler Arcade',allLanguages:'Wszystkie 12',feedSanta:'Nakarm Mikołaja',trucks:'Wielkie pojazdy',balloons:'Balony z liczbami',animals:'Zwierzęta',chooseGame:'Wybierz grę',previousGame:'Poprzednia gra',nextGame:'Następna gra',chooseLanguage:'Język',gamesLabel:'Gry',menuLabel:'Menu gier',playNow:'Graj',swipeForGames:'Przesuń po więcej gier',hideControls:'Ukryj przyciski',showControls:'Gry i języki',randomGame:'Gra niespodzianka',randomLanguageGame:'Losowa gra i język',playTimer:'Ustaw czas gry',playTimerTitle:'Czas gry',playTimerPrompt:'Jak długo się bawimy?',minutesShort:'min',noTimer:'Bez limitu',cancel:'Anuluj',timeUpTitle:'Koniec!',timeUpMessage:'Świetna zabawa. Czas na przerwę!',moreTime:'Dorosły: dodaj czas',
            santaPrompt:'Ari czym nakarmimy Mikołaja? 🎅',morePlease:'Co teraz zje Mikołaj Ari? 🎅',tickle:'Ho ho ho! To łaskocze Ari! 😆',santaLaugh:'Ho! Ho! Ho!',dragFood:'Przeciągnij lub dotknij jedzenia',popBalloons:'Przebij balony! 🎈',popped:n=>'Balon numer '+n+' pękł! ⭐',balloonLevelUp:n=>'Brawo! Teraz od 1 do '+n+'! 🚀',santaLabel:'Święty Mikołaj',
            everyday:'Codzienne rzeczy',letters:'Ogród liter',shapes:'Kolory i kształty',counting:'Policz i wybierz',body:'Ciało',runner:'Złap brokuł',music:'Studio muzyczne',beat:'Powtórz rytm',dance:'Tańcz i stop',bells:'Dzwonki Mikołaja',everydayPrompt:'Poznaj sześć rzeczy',everydayExplore:'👀 Odkrywaj',everydayFind:'👆 Dotknij',everydayMore:'Więcej rzeczy →',findQuestion:item=>'Dotknij '+item,findTry:'Spójrz jeszcze raz',findFound:()=>'To jest to!',findNext:'▶ Następny',findReal:()=>'Czy znajdziesz coś takiego obok siebie?',
            letterPrompt:'Dotknij litery',letterPhrase:item=>item.name+'. '+item.letter+' jak '+item.word+'.',shapePrompt:(color,shape)=>'Dotknij. Kolor '+color+'. Kształt '+shape+'.',shapeTry:'Spójrz jeszcze raz',shapeGreat:'Masz!',countPrompt:'Ile ich jest?',countTry:'Policz jeszcze raz',countGreat:n=>n+'! Brawo!',bodyPrompt:'Dotknij części ciała',bodyHint:'Dotknij postaci',runnerPrompt:'Przytrzymaj aby lecieć · Puść aby opaść',runnerHint:'Przytrzymaj aby lecieć',runnerRotate:'Obróć telefon na bok',runnerTutorial:'Przytrzymaj aby lecieć · Puść aby opaść',runnerCaught:(food,score)=>food+'! '+(score===1?'Jeden punkt':score+' punktów')+'!',runnerOw:'Au!',
            musicPrompt:'Graj muzykę',musicTogether:'Grajcie na zmianę',beatPrompt:'Popatrz na rytm',beatStart:'Dotknij tańczącego misia',beatNext:'▶ Nowy rytm',beatReady:'Gotowy? Dotknij tańczącego misia.',beatExplain:'Popatrz na rytm. Potem go powtórz. Gotowy?',beatYourTurn:'Teraz ty!',beatGreat:'Pamiętałeś!',beatPraise:['Brawo!','Bardzo dobrze!','Udało się!','Wspaniale!'],beatAgain:'Popatrz jeszcze raz na ten sam rytm',danceReady:'Gotowy?',danceStart:'▶ Tańcz',danceStop:'■ Stop',danceTogether:'Zróbcie miejsce i tańczcie razem',bellsPrompt:'Graj z Mikołajem',bellsSantaAction:'Posłuchaj Mikołaja',bellsBellAction:'Zadzwoń dużym dzwonkiem',jingleStart:'🎶 Zagraj Jingle Bells',jingleStop:'■ Zatrzymaj piosenkę'
        },
        settings:{button:'Ustawienia rodzica',title:'Ustawienia rodzica',greekNames:'🇬🇷 Imiona po grecku',otherNames:'🌍 Imiona w innych językach',help:'Oddziel przezwiska przecinkami. Zachowaj tę samą kolejność.',required:'Wpisz co najmniej jedno imię.',error:'Obie listy muszą mieć tyle samo imion.',close:'Zamknij',cancel:'Anuluj',save:'Zapisz',restore:'Przywróć domyślne',setup:'🌍 Języki i konfiguracja',diceTitle:'🎲 Co robi kostka?',diceSingle:'Jeden język',diceMultilingual:'Wszystkie języki',diceRandom:'Losowy język',timer:'Czas gry',soundCredits:'🔊 Źródła prawdziwych dźwięków'},
        onboarding:{step:n=>'Krok '+n+' z 3',primaryTitle:'Jaki jest główny język gry?',primaryLead:'Pojawi się pierwszy i będzie używany w menu.',languagesTitle:'Jakie języki ma słyszeć dziecko?',languagesLead:'Dodaj inne języki. Możesz je później zmienić.',languageMain:'Główny',languageCount:n=>n+' języków włączonych',addLanguage:'+ Dodaj język',allLanguagesAdded:'Dodano wszystkie języki',localeHint:'✨ Wybrano na podstawie języka i regionu urządzenia',namesTitle:'Jak gra ma nazywać dziecko?',namesLead:'Opcjonalnie: wpisz imiona tak jak mają brzmieć albo pomiń.',greekLabel:'🇬🇷 Po grecku',otherLabel:'🌍 W innych językach',namesHelp:'Opcjonalnie. Oddziel imię i przezwiska przecinkami.',back:'Wstecz',next:'Dalej',finish:'Zapisz i graj',skipNames:'Pomiń teraz',close:'Zamknij',required:'Wpisz co najmniej jedno imię.',mismatch:'Obie listy muszą mieć tyle samo imion.'},
        danceMoves:['Tańcz!','Klaszcz!','Biegaj w kółko!','Skacz!','Obróć się!','Ręce do góry!'],
        freeze:'Stop!',
        leader:'Teraz ty!',
        santaThanks:(food,foodName,name,variant)=>[
            food+'! Dziękuję za '+foodName+' '+name+'!',
            food+'! To było pyszne! Dziękuję '+name+'!',
            food+'! Bardzo mi smakowało! Dziękuję '+name+'!'
        ][variant]
    });
})();
